[package]
name = "bencode"
version = "0.1.0"
authors = ["Jonas Mathisrud Sterud <jonas.sterud@gmail.com>"]
description = "BitTorrent client, written in Rust ðŸ¦€"
repository = "https://github.com/jonassterud/thales"
license = "MIT"
edition = "2021"

[dependencies]
maplit = "1.0.2"
anyhow = "1.0.57"